### ISSUE TITLE
does not discard youtube tabs

### ISSUE THREAD

**Issue by mailinglists35** [rNeomy/auto-tab-discard#19]
![image](https://user-images.githubusercontent.com/2054302/36333718-140c97b0-1381-11e8-896e-4cc4a927b01f.png)

addons installed: umatrix ublock
settings altered: media.autoplay.enabled=false
youtube tab does not begin playing (because above setting)

i switch to another tab then right click on youtube tab - force discard - no effect (still see it on about:performance, i see it open when i click it)

**Comment by rNeomy** [comment]
I can reproduce this. Seems like a Firefox bug. This extension sends the discarding signal and FF is supposed to discard the tab. You can see the signal in the console if you enable logging.

To confirm, check this on Chrome. It discards the YouTube tab if it is not active.

**Comment by rNeomy** [comment]
Have you tried on FF 59? It works for me.

**Comment by mailinglists35** [comment]
latest available release version is 58 on my computer. this means it was a bug and fixed in v59?

**Comment by rNeomy** [comment]
Yes, Firefox's discarding API is new so it is still buggy. FF59 discards YouTube just fine.
