### ISSUE TITLE
Chrome Mouseover Tab Immediately Restores Tab

### ISSUE THREAD

**Issue by megamorphg** [rNeomy/auto-tab-discard#212]
Chrome has a new feature where we can mouse over the tab to get a preview of the tab. However, this feature undiscards a tab immediately on mouseover.

This is a problem when I mouse over tabs looking for the right tab to restore.

**Comment by rNeomy** [comment]
I don't think we can do anything about this problem from the extension side. This must get fixed by Chrome.

**Comment by rNeomy** [comment]
There is nothing much we can do. However, you can disable the preview from "chrome://flags/" -> "Tab Hover Cards"

**Comment by megamorphg** [comment]
As of the latest update, Chrome has removed the hovercard disabling flag.
I hope there is a way to get around this without becoming like the Suspender and redirecting URLs to browser extensions page. I like the way Discarder works better.

**Comment by rNeomy** [comment]
I tried the latest version of Chromium, and it looks like this bug is fixed. Placing the mouse over a discarded tab does not release the discarding state anymore.

**Comment by rNeomy** [comment]
Please confirm the fix or reopen.

**Comment by heavydoc** [comment]
Please reopen bug, as bug still exists. Mouse-over of any discarded tab will un-discard the tab. This bug is consistent for me although it doesn't always happen immediately, sometimes it's several seconds (~10) after mouse-over.

This causes problems for me when searching for a tab; tabs will un-discard causing slowdown and eating up memory. Using Chrome (111.0.5563.65 (Official Build) (64-bit)), on Windows 11.
