### ISSUE TITLE
Unexpected discard of all tabs, even though automatic discarding is disabled

### ISSUE THREAD

**Issue by zanglebert** [rNeomy/auto-tab-discard#78]
(I'm using auto-tab-discard v0.3.1 in FF 65.0.1)

According to the addon settings I I'm using (with seconds set to 0), there shouldn't be any tab discarding, unless I provide the user command triggering it. In other words: I shouldn't get any automatic tab discarding.

Yet, if I open a very large number of tabs, the addon seems to trigger a "suspend all inactive" call. Is that observation correct, and if so, shouldn't it be documented? (perhaps it is and I missed it -- sorry then).

**Comment by zanglebert** [comment]
Anyone able to reproduce?

I can't pinpoint the exact number when this happens, but from some (high) number of open tabs, the 'discard' function kicks in, even though automatic calls are disabled in the settings.

**Comment by dverbru** [comment]
Same issue here. I usually have around a hundred tabs open and many of them get discarded from time to time, even when I'm using that magic 0 seconds value to disable auto-discard.

**Comment by Luckz** [comment]
I have this on Chrome 78. After a while, it will start unloading every tab when set to 0 seconds & 6 tabs. The effective workaround is setting the minimum tab number to discard to 99999.

This is with >1000 tabs. ^_^

**Comment by rNeomy** [comment]
hopefully it is fixed!

**Comment by Luckz** [comment]
Unfortunately this is still happening to me. At unclear times, tabs are discarded, and I'm not sure why. They get the ATD favicon so I assume it's auto tab discard doing it and not Chrome's automagic crazy logic?

![image](https://user-images.githubusercontent.com/224748/71229736-0c74ea80-22e7-11ea-8996-d83f0913c6e9.png)

**Comment by Luckz** [comment]
Re-enabled the extension and after a while it began happening again that Chrome aggressively discards the tabs I was using. @rNeomy
